openapi: 3.0.3
info:
  title: OtusShop - OpenAPI 3.0
  description: |-
    Описание API интернет-магазина на основе спецификации OpenAPI 3.0.
  version: 1.0.0
servers:
  - url: https://127.0.0.1:8081/api/v1/orders
tags:
  - name: orders
    description: 'Операции над заказами'
paths:
          
  /list:
    get:
      tags:
        - orders
      summary: 'Получить список заказов'
      description: ''
      operationId: getOrdersList
      parameters:
        - name: currentUserId
          in: query
          description: 'ID пользователя, который выполняет запрос.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Операция выполнена'
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Order'
        '400':
          description: 'Некорректные параметры запроса'

  /create:
    post:
      tags:
        - orders
      summary: 'Создать заказ'
      description: ''
      operationId: createOrder
      parameters:
        - name: currentUserId
          in: query
          description: 'ID пользователя, который выполняет запрос.'
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: 'Операция выполнена'
        '400':
          description: 'Некорректные параметры запроса'
          
  /cancel:
    post:
      tags:
        - orders
      summary: 'Отменить заказ'
      description: ''
      operationId: cancleOrder
      parameters:
        - name: currentUserId
          in: query
          description: 'ID пользователя, который выполняет запрос.'
          required: true
          schema:
            type: string
        - name: orderID
          in: query
          description: 'ID заказа.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Операция выполнена'
        '400':
          description: 'Некорректные параметры запроса'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: 'ID товара'
          format: uuid
          example: "579182b1-6537-48c9-b1b6-8105ec1ceb39"
        name:
          type: string
          example: "Товар1"
        price:
          type: integer
          example: 123
        
    Order:
      type: object
      properties:
        id:
          type: string
          description: 'ID заказа'
          format: uuid
          example: "579182b1-6537-48c9-b1b6-8105ec1ceb39"
        products:
          type: object
          description: 'Список товаров в заказе'
          properties:
            option:
              type: array
              items:
                  $ref: '#/components/schemas/Product'
        shippingTo:
          type: string
          description: 'Адрес доставки'
          example: "ул. Ленина, д. 12, кв. 51"
        cardParams:
          type: string
          description: 'Номер карты'
          example: "1234 5678 1234 5678; 345; Ivan Ivanov"
        status:
          type: string
          description: 'CREATED/CANCELED/PAYED/RESERVED/DELIVERED'
          example: "CREATED"
