apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment-auth
  labels:
    app: users-service-auth
spec:
  selector:
    matchLabels:
      app: users-service-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: users-service-auth
    spec:
      containers:
        - name: users-service-auth
          image: julinserg/auth_service_auth_docker_image:latest
          ports:
            - containerPort: 9000
          env:
            - name: USC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: users-service-configmap
                  key: loglevel
            - name: USC_HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-service-configmap
                  key: httphost
            - name: USC_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-service-configmap
                  key: httpportauth
            - name: USC_PG_HOST
              value: "pg1-postgresql"
            - name: USC_PG_USER
              value: "postgres"
            - name: USC_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-service-secret
                  key: password
            - name: USC_PG_DB
              value: "users"
