apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: julinserg/orders_service_shop_docker_image:latest
          ports:
            - containerPort: 8090
          env:
            - name: USC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: loglevel
            - name: USC_HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: httphost
            - name: USC_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-service-configmap
                  key: httpport
            - name: USC_PG_HOST
              value: "pg1-postgresql"
            - name: USC_PG_USER
              value: "postgres"
            - name: USC_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: password
            - name: USC_PG_DB
              value: "users"
