apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users-service-monitor
  labels:
    app: users-service-monitor  
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http      
  selector:
    matchLabels:
      app: users-service
  
